CREATE TYPE hubungan AS ENUM (
    'suami/istri',
    'anak',
    'ayah',
    'ibu',
    'saudara laki-laki',
    'saudara perempuan'
);

CREATE TYPE jenis_kelamin AS ENUM (
    'L',
    'P'
);

CREATE TYPE role AS ENUM (
    'admin',
    'pegawai'
);

CREATE TABLE status_pegawai (
    id bigint generated by default as identity primary key,
    status text
);

CREATE TABLE jenis_pegawai (
    id bigint generated by default as identity primary key,
    jenis text
);

CREATE TABLE jabatan (
    id bigint generated by default as identity primary key,
    nama text
);

CREATE TABLE "user" (
    id bigint generated by default as identity primary key,
    username text,
    password text,
    role role,
    token text
);

CREATE TABLE pegawai (
    id bigint generated by default as identity primary key,
    nip text,
    nama text,
    tempat_lahir text,
    tanggal_lahir date,
    agama text,
    no_telpon text,
    email text,
    id_jabatan bigint not null REFERENCES public.jabatan ON UPDATE CASCADE ON DELETE RESTRICT,
    id_jenis_pegawai bigint not null REFERENCES public.jenis_pegawai ON UPDATE CASCADE ON DELETE RESTRICT,
    id_status_pegawai bigint not null REFERENCES public.status_pegawai ON UPDATE CASCADE ON DELETE RESTRICT,
    jenis_kelamin jenis_kelamin,
    id_user bigint not null REFERENCES public."user"
);

CREATE TABLE cuti (
    id bigint generated by default as identity primary key,
    jumlah bigint,
    tanggal_awal date,
    tanggal_akhir date,
    status text,
    id_pegawai bigint not null REFERENCES public.pegawai ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE keluarga (
    id bigint generated by default as identity primary key,
    hubungan hubungan,
    nama text,
    id_pegawai bigint not null REFERENCES public.pegawai ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE mutasi (
    id bigint generated by default as identity primary key,
    jenis text,
    tanggal date,
    tujuan text,
    nomor_sk text,
    tanggal_sk date,
    file_sk text,
    id_pegawai bigint not null REFERENCES public.pegawai ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE pendidikan (
    id bigint generated by default as identity primary key,
    universitas_sekolah text,
    jurusan text,
    tanggal_masuk date,
    tanggal_lulus date,
    gelar text,
    nilai text,
    id_pegawai bigint not null REFERENCES public.pegawai ON UPDATE CASCADE ON DELETE CASCADE,
    jenjang text
);

CREATE TABLE riwayat_jabatan (
    id bigint generated by default as identity primary key,
    id_pegawai bigint not null REFERENCES public.pegawai ON UPDATE CASCADE ON DELETE CASCADE,
    id_jabatan bigint not null REFERENCES public.jabatan ON UPDATE CASCADE ON DELETE CASCADE
);

insert into status_pegawai (status) values ('Aktif'), ('Non Aktif');

insert into jenis_pegawai (jenis) values ('Tetap'), ('Ojt/Magang');

insert into jabatan (nama) values ('Manager'), ('Supervisor'), ('General Manager'), ('Officer');

insert into "user" (username, password, role, token) values ('admin','$2a$12$.Gq7wO.EVSgrCT3cS5r0fev3lawHEC1ZaJBnbMecYqAg5ibJa1f1a', 'admin', 'N');

insert into pegawai (nip, nama, tempat_lahir, tanggal_lahir, agama, no_telpon, email, id_jabatan, id_jenis_pegawai, id_status_pegawai, jenis_kelamin, id_user) values
('2000000120005', 'Deri Setiawan', 'Lampung', '1998-11-05', 'Islam', '089712345678', 'deri@mail.com', 1, 1, 1, 'L', 1);

insert into riwayat_jabatan (id_pegawai, id_jabatan) values (1, 1), (1, 2);

insert into cuti (jumlah, tanggal_awal, tanggal_akhir, status, id_pegawai) values (1, '2022-12-11', '2022-12-12', 'N', 1);

insert into keluarga (hubungan, nama, id_pegawai) values ('suami/istri', 'Rina Dwi Aryani', 1), ('anak', 'Nurmawati', 1);

insert into mutasi (jenis, tanggal, tujuan, nomor_sk, tanggal_sk, file_sk, id_pegawai) values

('Pengangkatan Jabatan', '2022-08-10', 'Kemana', 'SK.17/M/I/8', '2022-08-10', 'uploads/file_sk1670766539140.pdf', 1);

insert into pendidikan (universitas_sekolah, jurusan, tanggal_masuk, tanggal_lulus, gelar, nilai, id_pegawai, jenjang) values
('Universitas Lampung', 'Ekonomi', '2015-07-20', '2019-10-20', 'Sarjana Ekonomi', '3.56', 1, 'S1'),
('Universitas Sriwijaya', 'Ekonomi dan Statiska', '2019-11-10', '2022-10-11', 'Magister Ekonomi', '3.8', 1, 'S2');

